name: build
on:
  push:
    branches:
      - master      

jobs:
  mac:
    name: mac-build
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts
      - run: |
          npm i -g npm-license-generator 
          git clone https://github.com/hiyok0/Nimos.git
          cd Nimos/main
          npm ci
          npm-license-generator --template ../template.hbs --package-lock --out-path ./html/static/opensorcelicenses/index.html
          npm run make
          echo nimosVer=$(node -e 'console.log(require("./package.json").version)') >> $GITHUB_ENV
          echo commitMessage=$(git log --oneline --pretty=format:%s | head -n 1) >> $GITHUB_ENV
          mv out/make/zip/darwin/x64/Nimos-darwin-x64-*.zip out/make/zip/darwin/x64/Nimos.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Nimos_v${{ env.nimosVer }}.zip
          path: Nimos/main/out/make/zip/darwin/x64/Nimos.zip
      
      - uses: softprops/action-gh-release@v2
        if: startsWith(env.commitMessage, "Release:")
        with:
          draft: true
          prerelease: true
          files: Nimos/main/out/make/zip/darwin/x64/Nimos.zip
          name: "Release: ${{ env.nimosVer }}"
          tag_name: "v${{ env.nimosVer }}"
          repository: hiyok0/Nimos
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: false
