name: build
on:
  push:
    branches:
      - master      

jobs:
  mac:
    name: mac-build
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm i -g npm-license-generator 
          git clone https://github.com/hiyok0/nusuttoChan.git
          cd nusuttoChan/main
          npm ci
          npm-license-generator --template ../template.hbs --package-lock --out-path ./html/static/opensorcelicenses/index.html
          #一応実行↓
          npx electron-forge import
          npm run make
          cp out/make/zip/darwin/x64/nusuttochan-darwin-x64-*.zip ../nusuttochan-darwin-x64.zip
          
      - uses: actions/upload-artifact@v3
        with:
          name: nusuttoChan_${{ github.sha }}
          path: nusuttoChan/out/make/zip/darwin/x64/nusuttochan-darwin-x64-*.zip
          
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: nusuttoChan/main
      
      - name: MakeARelease
        uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: true
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: UploadArtifactToRelease
        uses: nanoufo/action-upload-artifacts-and-release-assets@main
        if: ${{ steps.MakeARelease.released }}
        with:
          path: |
            nusuttoChan/nusuttochan-darwin-x64.zip
          upload-release-files: true
          release-upload-url: ${{ steps.MakeARelease.upload_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
