name: build
on:
  push:
    branches:
      - master      

jobs:
  mac:
    name: mac-build
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm i -g npm-license-generator &
          git clone https://github.com/hiyok0/nusuttoChan.git
          cd nusuttoChan/main
          npm ci
          $!
          npm-license-generator --template ../template.hbs --package-lock --out-path ./html/static/opensorcelicenses/index.html
          #一応実行↓
          npx electron-forge import
          npm run make
          cp out/make/zip/darwin/x64/nusuttochan-darwin-x64-*.zip ../nusuttochan-darwin-x64.zip
          
      - uses: actions/upload-artifact@v3
        with:
          name: nusuttoChan_${{ github.sha }}
          path: nusuttoChan/out/make/zip/darwin/x64/nusuttochan-darwin-x64-*.zip
          
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: nusuttoChan/main
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.event.head_commit.message, '__Release: ')"
        with:
          draft: true
          prerelease: true
          tag-name: v${{ steps.package-version.outputs.current-version}}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: nusuttoChan/nusuttochan-darwin-x64.zip
